[versions]
android-sdk-compile = "34"
android-sdk-target = "34"
android-sdk-min = "24"
agp = "8.8.1"
gms = "4.4.2"

kotlin = "1.9.25"
coroutines = "1.10.1"
ksp-plugin = "1.9.25-1.0.20"

hilt = "2.55"
navigation = "2.8.7"
room = "2.6.1"
lifecycle = "2.8.7"
camera = "1.4.1"

okhttp = "4.12.0"
retrofit = "2.11.0"
moshi = "1.15.2"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

dagger-hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
dagger-hilt-fragment = "androidx.hilt:hilt-navigation-fragment:1.2.0"

androidx-activity = "androidx.activity:activity-ktx:1.10.0"
androidx-autofill = "androidx.autofill:autofill:1.1.0"
androidx-biometric = "androidx.biometric:biometric-ktx:1.4.0-alpha02"
androidx-concurrent = "androidx.concurrent:concurrent-futures-ktx:1.2.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.0"
androidx-core = "androidx.core:core-ktx:1.15.0"
androidx-localBroadcastManager = "androidx.localbroadcastmanager:localbroadcastmanager:1.1.0"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.4.0"
androidx-splashscreen = "androidx.core:core-splashscreen:1.0.1"
androidx-testing-core = "androidx.test:core-ktx:1.6.1"
androidx-testing-epsresso = "androidx.test.espresso:espresso-core:3.6.1"
androidx-testing-junit = "androidx.test.ext:junit-ktx:1.2.1"
androidx-testing-rules = "androidx.test:rules:1.6.1"
androidx-testing-uiautomator = "androidx.test.uiautomator:uiautomator:2.4.0-alpha01"

androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-scope = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

androidx-navigation-gradle = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-sqlite = "androidx.sqlite:sqlite-ktx:2.4.0"

androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }

google-gms-gradle = "com.google.gms:google-services:4.4.2"
google-android-material = "com.google.android.material:material:1.12.0"
google-mlkit-barcode = "com.google.mlkit:barcode-scanning:17.3.0"
google-firebase-messaging = "com.google.firebase:firebase-messaging-ktx:23.4.1"

okhttp-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }

moshi-moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

permission = "com.github.fondesa:kpermissions:3.5.0"
coil = "io.coil-kt:coil:2.7.0"
betterLink = "me.saket:better-link-movement-method:2.2.0"
timber = "com.jakewharton.timber:timber:5.0.1"

junit = "junit:junit:4.13.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-plugin" }
safe-args = {id = "androidx.navigation.safeargs.kotlin", version.ref="navigation"}
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-gms-gradle = { id = "com.google.gms.google-services", version.ref = "gms" }